# Halo Blog 配置
halo:
  blog:
    base-url: https://yaemiko.live
    pat: ${HALO_PAT:your-pat-token-here}
    default-owner: admin

spring:
  application:
    name: mcp-server-halo

  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

  main:
    banner-mode: off
#     stdio 模式打开，sse 模式，注释掉。
    web-application-type: none

# 日志配置
logging:
  # stdio 模式打开，sse 模式，注释掉。
  pattern:
    console: ""
  file:
    name: data/log/${spring.application.name}.log


server:
  port: 8101
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true